"""add model

Revision ID: 00141dd742d2
Revises: eb5e1abe3f3d
Create Date: 2025-10-16 01:06:35.011900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00141dd742d2'
down_revision: Union[str, None] = 'eb5e1abe3f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_rule_associations')
    op.drop_table('regulatory_references')
    op.drop_index('ix_validation_results_calculation_result_id', table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_table('audit_trails')
    op.drop_index('ix_designated_reps_email', table_name='designated_reps')
    op.drop_index('ix_designated_reps_facility_id', table_name='designated_reps')
    op.drop_index('ix_designated_reps_id', table_name='designated_reps')
    op.drop_table('designated_reps')
    op.drop_table('calculation_data_associations')
    op.drop_index('ix_regulatory_rules_rule_type', table_name='regulatory_rules')
    op.drop_index('ix_regulatory_rules_subpart', table_name='regulatory_rules')
    op.execute("""
DROP TABLE regulatory_rules CASCADE
""")
    op.drop_table('regulatory_documents')
    op.drop_index('ix_calculation_results_facility_id', table_name='calculation_results')
    op.execute("""
    DROP TABLE calculation_results CASCADE
""")
    op.drop_index('ix_emissions_data_data_type', table_name='emissions_data')
    op.drop_index('ix_emissions_data_facility_id', table_name='emissions_data')
    op.drop_index('ix_emissions_data_reporting_period_end', table_name='emissions_data')
    op.drop_index('ix_emissions_data_reporting_period_start', table_name='emissions_data')
    op.execute("""
    DROP TABLE emissions_data CASCADE
""")
    op.drop_index('ix_measurements_emissions_data_id', table_name='measurements')
    op.drop_index('ix_measurements_timestamp', table_name='measurements')
    op.drop_table('measurements')
    op.drop_index('ix_calculation_steps_calculation_result_id', table_name='calculation_steps')
    op.drop_table('calculation_steps')
    op.drop_table('self_validation_results')
    op.add_column('users', sa.Column('facility_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.execute("UPDATE users SET role='USER' WHERE role IS NULL")
    op.alter_column('users', 'role', nullable=False)
    op.create_index(op.f('ix_users_facility_id'), 'users', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'users', 'facilities', ['facility_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_facility_id'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'facility_id')
    op.create_table('self_validation_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('calculation_result_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alternative_methods', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cross_reference_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('historical_comparison', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('overall_confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('discrepancies_found', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('requires_manual_review', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('variance_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_intervals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], name='self_validation_results_calculation_result_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='self_validation_results_pkey'),
    sa.UniqueConstraint('calculation_result_id', name='self_validation_results_calculation_result_id_key')
    )
    op.create_table('calculation_steps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('calculation_result_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('formula_used', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('input_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('output_value', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False),
    sa.Column('units', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('applied_rule_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('intermediate_calculations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['applied_rule_id'], ['regulatory_rules.id'], name='calculation_steps_applied_rule_id_fkey'),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], name='calculation_steps_calculation_result_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='calculation_steps_pkey')
    )
    op.create_index('ix_calculation_steps_calculation_result_id', 'calculation_steps', ['calculation_result_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('emissions_data_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('parameter_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quality_flag', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('uncertainty', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('measurement_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('instrument_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['emissions_data_id'], ['emissions_data.id'], name='measurements_emissions_data_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='measurements_pkey')
    )
    op.create_index('ix_measurements_timestamp', 'measurements', ['timestamp'], unique=False)
    op.create_index('ix_measurements_emissions_data_id', 'measurements', ['emissions_data_id'], unique=False)
    op.create_table('emissions_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reporting_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reporting_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('measurements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('quality_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('validation_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ingestion_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name='emissions_data_facility_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='emissions_data_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_emissions_data_reporting_period_start', 'emissions_data', ['reporting_period_start'], unique=False)
    op.create_index('ix_emissions_data_reporting_period_end', 'emissions_data', ['reporting_period_end'], unique=False)
    op.create_index('ix_emissions_data_facility_id', 'emissions_data', ['facility_id'], unique=False)
    op.create_index('ix_emissions_data_data_type', 'emissions_data', ['data_type'], unique=False)
    op.create_table('calculation_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('calculation_method', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('calculation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('final_result', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False),
    sa.Column('units', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('validation_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('calculation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reporting_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reporting_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('input_data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('applied_rules_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name='calculation_results_facility_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='calculation_results_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_calculation_results_facility_id', 'calculation_results', ['facility_id'], unique=False)
    op.create_table('regulatory_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='regulatory_documents_pkey')
    )
    op.create_table('regulatory_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subpart', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rule_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('formula', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applicability_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('superseded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('source_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['superseded_by'], ['regulatory_rules.id'], name='regulatory_rules_superseded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='regulatory_rules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_regulatory_rules_subpart', 'regulatory_rules', ['subpart'], unique=False)
    op.create_index('ix_regulatory_rules_rule_type', 'regulatory_rules', ['rule_type'], unique=False)
    op.create_table('calculation_data_associations',
    sa.Column('calculation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('emissions_data_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation_results.id'], name='calculation_data_associations_calculation_id_fkey'),
    sa.ForeignKeyConstraint(['emissions_data_id'], ['emissions_data.id'], name='calculation_data_associations_emissions_data_id_fkey'),
    sa.PrimaryKeyConstraint('calculation_id', 'emissions_data_id', name='calculation_data_associations_pkey')
    )
    op.create_table('designated_reps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name='designated_reps_facility_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='designated_reps_pkey')
    )
    op.create_index('ix_designated_reps_id', 'designated_reps', ['id'], unique=False)
    op.create_index('ix_designated_reps_facility_id', 'designated_reps', ['facility_id'], unique=False)
    op.create_index('ix_designated_reps_email', 'designated_reps', ['email'], unique=True)
    op.create_table('audit_trails',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('calculation_result_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('input_data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('applied_rules_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('regulatory_citations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('system_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], name='audit_trails_calculation_result_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_trails_pkey'),
    sa.UniqueConstraint('calculation_result_id', name='audit_trails_calculation_result_id_key')
    )
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('calculation_result_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('validation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('validation_rule', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('requires_manual_review', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('validation_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('validated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], name='validation_results_calculation_result_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='validation_results_pkey')
    )
    op.create_index('ix_validation_results_calculation_result_id', 'validation_results', ['calculation_result_id'], unique=False)
    op.create_table('regulatory_references',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('citation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('effective_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content_excerpt', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='regulatory_references_pkey')
    )
    op.create_table('calculation_rule_associations',
    sa.Column('calculation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation_results.id'], name='calculation_rule_associations_calculation_id_fkey'),
    sa.ForeignKeyConstraint(['rule_id'], ['regulatory_rules.id'], name='calculation_rule_associations_rule_id_fkey'),
    sa.PrimaryKeyConstraint('calculation_id', 'rule_id', name='calculation_rule_associations_pkey')
    )
    # ### end Alembic commands ###
