"""initial tables

Revision ID: 1975dc16ad15
Revises: 
Create Date: 2025-10-09 03:11:47.744450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1975dc16ad15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('regulatory_jurisdiction', sa.JSON(), nullable=False),
    sa.Column('applicable_subparts', sa.JSON(), nullable=False),
    sa.Column('facility_metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_table('regulatory_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citation', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('content_excerpt', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subpart', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('applicability_criteria', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by'], ['regulatory_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_rules_rule_type'), 'regulatory_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_regulatory_rules_subpart'), 'regulatory_rules', ['subpart'], unique=False)
    op.create_table('calculation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('calculation_method', sa.String(length=255), nullable=False),
    sa.Column('calculation_type', sa.String(length=100), nullable=False),
    sa.Column('final_result', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('units', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('reporting_period_start', sa.DateTime(), nullable=False),
    sa.Column('reporting_period_end', sa.DateTime(), nullable=False),
    sa.Column('input_data_hash', sa.String(length=64), nullable=False),
    sa.Column('applied_rules_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_results_facility_id'), 'calculation_results', ['facility_id'], unique=False)
    op.create_table('emissions_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_start', sa.DateTime(), nullable=False),
    sa.Column('reporting_period_end', sa.DateTime(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('data_source', sa.String(length=255), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('validation_results', sa.JSON(), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emissions_data_data_type'), 'emissions_data', ['data_type'], unique=False)
    op.create_index(op.f('ix_emissions_data_facility_id'), 'emissions_data', ['facility_id'], unique=False)
    op.create_index(op.f('ix_emissions_data_reporting_period_end'), 'emissions_data', ['reporting_period_end'], unique=False)
    op.create_index(op.f('ix_emissions_data_reporting_period_start'), 'emissions_data', ['reporting_period_start'], unique=False)
    op.create_table('audit_trails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_result_id', sa.UUID(), nullable=False),
    sa.Column('input_data_hash', sa.String(length=64), nullable=False),
    sa.Column('applied_rules_hash', sa.String(length=64), nullable=False),
    sa.Column('regulatory_citations', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('system_version', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calculation_result_id')
    )
    op.create_table('calculation_data_associations',
    sa.Column('calculation_id', sa.UUID(), nullable=False),
    sa.Column('emissions_data_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation_results.id'], ),
    sa.ForeignKeyConstraint(['emissions_data_id'], ['emissions_data.id'], ),
    sa.PrimaryKeyConstraint('calculation_id', 'emissions_data_id')
    )
    op.create_table('calculation_rule_associations',
    sa.Column('calculation_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation_results.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['regulatory_rules.id'], ),
    sa.PrimaryKeyConstraint('calculation_id', 'rule_id')
    )
    op.create_table('calculation_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_result_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=255), nullable=False),
    sa.Column('formula_used', sa.Text(), nullable=True),
    sa.Column('input_values', sa.JSON(), nullable=False),
    sa.Column('output_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('units', sa.String(length=50), nullable=False),
    sa.Column('applied_rule_id', sa.UUID(), nullable=True),
    sa.Column('intermediate_calculations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_rule_id'], ['regulatory_rules.id'], ),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_steps_calculation_result_id'), 'calculation_steps', ['calculation_result_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('emissions_data_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quality_flag', sa.String(length=50), nullable=False),
    sa.Column('uncertainty', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('measurement_method', sa.String(length=100), nullable=True),
    sa.Column('instrument_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['emissions_data_id'], ['emissions_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_emissions_data_id'), 'measurements', ['emissions_data_id'], unique=False)
    op.create_index(op.f('ix_measurements_timestamp'), 'measurements', ['timestamp'], unique=False)
    op.create_table('self_validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_result_id', sa.UUID(), nullable=False),
    sa.Column('alternative_methods', sa.JSON(), nullable=False),
    sa.Column('cross_reference_sources', sa.JSON(), nullable=False),
    sa.Column('historical_comparison', sa.JSON(), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('discrepancies_found', sa.Boolean(), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('variance_analysis', sa.JSON(), nullable=True),
    sa.Column('confidence_intervals', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calculation_result_id')
    )
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_result_id', sa.UUID(), nullable=False),
    sa.Column('validation_type', sa.String(length=100), nullable=False),
    sa.Column('validation_rule', sa.String(length=255), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('validation_by', sa.String(length=50), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_calculation_result_id'), 'validation_results', ['calculation_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_calculation_result_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_table('self_validation_results')
    op.drop_index(op.f('ix_measurements_timestamp'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_emissions_data_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_calculation_steps_calculation_result_id'), table_name='calculation_steps')
    op.drop_table('calculation_steps')
    op.drop_table('calculation_rule_associations')
    op.drop_table('calculation_data_associations')
    op.drop_table('audit_trails')
    op.drop_index(op.f('ix_emissions_data_reporting_period_start'), table_name='emissions_data')
    op.drop_index(op.f('ix_emissions_data_reporting_period_end'), table_name='emissions_data')
    op.drop_index(op.f('ix_emissions_data_facility_id'), table_name='emissions_data')
    op.drop_index(op.f('ix_emissions_data_data_type'), table_name='emissions_data')
    op.drop_table('emissions_data')
    op.drop_index(op.f('ix_calculation_results_facility_id'), table_name='calculation_results')
    op.drop_table('calculation_results')
    op.drop_index(op.f('ix_regulatory_rules_subpart'), table_name='regulatory_rules')
    op.drop_index(op.f('ix_regulatory_rules_rule_type'), table_name='regulatory_rules')
    op.drop_table('regulatory_rules')
    op.drop_table('regulatory_references')
    op.drop_table('regulatory_documents')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
