"""add model

Revision ID: 4e30f9f0e31d
Revises: 1975dc16ad15
Create Date: 2025-10-15 08:10:53.529591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e30f9f0e31d'
down_revision: Union[str, None] = '1975dc16ad15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calculation_results_facility_id_fkey', 'calculation_results', type_='foreignkey')
    op.create_foreign_key(None, 'calculation_results', 'facilities', ['facility_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('emissions_data_facility_id_fkey', 'emissions_data', type_='foreignkey')
    op.create_foreign_key(None, 'emissions_data', 'facilities', ['facility_id'], ['id'], ondelete='CASCADE')
    op.alter_column('facilities', 'location',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'location',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(None, 'emissions_data', type_='foreignkey')
    op.create_foreign_key('emissions_data_facility_id_fkey', 'emissions_data', 'facilities', ['facility_id'], ['id'])
    op.drop_constraint(None, 'calculation_results', type_='foreignkey')
    op.create_foreign_key('calculation_results_facility_id_fkey', 'calculation_results', 'facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###
