"""add model

Revision ID: eb5e1abe3f3d
Revises: a6b5b03acd77
Create Date: 2025-10-15 09:45:05.282630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5e1abe3f3d'
down_revision: Union[str, None] = 'a6b5b03acd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE designated_reps
    ALTER COLUMN hashed_password
    TYPE BYTEA
    USING hashed_password::bytea
""")
    op.execute("""
    ALTER TABLE users
    ALTER COLUMN hashed_password
    TYPE BYTEA
    USING hashed_password::bytea
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('designated_reps', 'hashed_password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
